version: "3.7"

services:
  # Start an Nginx server to route requests to the Evaluations Service
  # It is mainly used for CORS stuff.
  nginx:
    image: shakyshane/nginx-cors-plus
    depends_on: 
      - evaluations-service
    ports: 
      - "8000:80"
    networks: 
      - dmz       # Provide services to the Internet
      - services  # Allow communications with the services network
    environment:
      TARGET: "http://evaluations-service:8000"

  # Starts a container with the Evaluations Service.
  evaluations-service:
    image: itbacep/evaluations-service:${EVALUATIONS_SERVICE_VERSION}
    depends_on: 
      - postgres
    ports:
      - "8000:8000"
    networks:
      - services
      - databases
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  
  # Starts a container with a Postgres Database.
  postgres:
    image: debezium/postgres:10-alpine
    ports:
      - "8001:5432"
    networks:
      - databases
      - backdoor
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    

networks:
  # Network that can be accessed from the outside
  dmz:
    name: dmz
    driver: bridge
  # Network where services are placed
  services:
    name: services
    driver: bridge
    internal: 'true'
  # Network where databases are placed
  databases:
    name: databases
    driver: bridge
    internal: 'true'
  # A network to be used for troubleshooting and debugging 
  # DO NOT USE IN PRODUCTION!!!
  backdoor:
    name: backdoor
    driver: bridge
