version: "3.7"


# ================================================================================
# Services
# ================================================================================

services:
  
  # ================================================================================
  # API gateway
  # ================================================================================

  api-gateway:
    image: itbacep/api-gateway:${API_GATEWAY_VERSION}
    depends_on:
      - evaluations-service
      - playground-service
      - service-registry
    ports:
      - "8000:80"
    networks:
      - dmz       # Provide services to the Internet
      - services  # Allow communications with the services network
      - databases # Allow communications with the databases
    environment:
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"
      AUTHENTICATION_JWT_EXTERNAL_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB
      AUTHENTICATION_JWT_INTERNAL_PRIVATEKEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDdCiV3aMzOT8JrfJi6yOb2HE2ncRUGfNYPwZtNJ809X7vP/7Z/0tFLHYLO0wLCA9yIoL7t9YfMpxSCJ0ts+o+kqOqVslDQoqnus8c5OYBpJpVf45VKLTSnuVtTUd16mN3O3QtPBPcQEdNTR8aCFM5Bl99W0rPKDga2HqIoSEgAdDO1DrckjlzoXWjh4bAnwmsgdyNR7Bc7wcMGxT7dQa2LDyLFdVnix8YytaQ/KUALzWAJYV9CFaCAbPQ73EwQEPfQLUSAEFkQ3wLRaDcSAMi2JSu52q/FyCcJrWyyMSBJj6RiAywPByqnM7k+IhI13YkhzfWaIz31dpCQCtgiJ0FPAgMBAAECggEAa2DLdKevnqX2f7rmgw6nzHVRb/8qRJ2Oa9cUt7WXKbKBDXle0de7Hq92ZTzywQeZMbJNLlIxp0SfXN7z8DwEXexFEXWvdrserDwfkvgRHoPE2vE3C/LL+pK7/8zsN+tdDWoqXTe/Qco3C+T5VSYAULMTpxzyhDyuG/jjs4fxmm3xhi5OlUc4Ffh1MMdldkzp2fw2V58dJn1iwUyv/Up/VpxvIihqLcOXY6mRoXsAlFXlClG367QxuAyVZMzb6MtAg/tmTRQ8rCN9d3/piqIdtrF/2dI/B6QfeQNtqvY7o6Sq/lBvPqpv5hPeE6kX9J/nGCbfK95uR3Nh3o5jSWmm8QKBgQD3nx4JXZjZXO+9N04QnahZTWj819OVyg1VWBEb7obfDkhOqJEgQFBg7yadmtI/NwIFaEonJ3N6e5qimuFlEPGMhNFDxJvgxK9xKH1tig61RYP27NwkFvHLhiDMQyRx1t5VX37DdeTtvEOn/jDl8i41EJyGvnacvsk2XT4b1qIdFwKBgQDkhMcwem9Qu3gAfQ1UR011Srp1FjDxpqBGnSu6MPFuirSX/m+cyUgthZ2R1q3glZKQ1OaJihqx9jNeotHGcQeXXW+nFnlqxxk+Dt2LHurYJcAmynPdSqNBmtQlQl3h2tg84rpVtYuFkEs+GRY4fzilZqkk7G9VEx9tRadauDXQiQKBgQCtdNTBksMDYEq/rQIOOaI4DDXDCBy7DLKSWgKCInBvx712/DXM9cBYZq4SMOWeSpYr24Y2LziBUBxeU0gYV+ocmN1OL2dR5/VNuyNBnDf5Wxy51+nNjhUKkIZhD5dz9yP/gcl2ehtHPV3XTARMz3z2xxAeg0TrP+oLHv3m2k7tOQKBgAik2SAFUZadMMHb+RgaBl0McZciOsG5StDA+zl0xn0m9APX1QL6PieyqS4uD6+yGLQvyXSka7QVmwXWZNb7yYy5NRL976PRWiwVxd2QUtPQQb914wIY46oEoEe0hfaYH5vV+7RoRJnNxnrX2hZTAaKICpfh9agjLAonG1h8JVT5AoGBAIl3qIMVbPPmKRveZxJ+17RRveWu+vXD3PbxWxREQMBqFuk+pPemMMoFbSVevs33cOx7m7kZ9zsgs7JkLqjAx2RqL+JtCBgkFVbwd3QMkUS7mKPIljv/cUbUOcpVZmeV6C0UBHPgMyUltbHIhmVI+d4JafTCV384y0Cv0NcRFn1/

  # ================================================================================
  # Playground Service
  # ================================================================================
  
  # Starts a container with the Playground Service
  playground-service:
    image: itbacep/playground-service:${PLAYGROUND_SERVICE_VERSION}
    depends_on:
      - service-registry
      - postgres-playground
      - kafka
    networks:
      - services
      - databases
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-playground:5432/${PLAYGROUND_SERVICE_POSTGRES_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${PLAYGROUND_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${PLAYGROUND_SERVICE_POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"
      AUTHENTICATION_JWT_APIGATEWAY_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB

  # Starts a container with a Postgres Database for the Playground Service.
  postgres-playground:
    image: postgres:10.8-alpine
    ports:
      - "15432:5432"
    networks:
      - databases
      - backdoor
    environment:
      POSTGRES_USER: ${PLAYGROUND_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PLAYGROUND_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PLAYGROUND_SERVICE_POSTGRES_DATABASE}


  # ================================================================================
  # Evaluations Service
  # ================================================================================
  
  # Starts a container with the Evaluations Service.
  evaluations-service:
    image: itbacep/evaluations-service:${EVALUATIONS_SERVICE_VERSION}
    depends_on:
      - service-registry
      - postgres-evaluations
      - kafka
    networks:
      - services
      - databases
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-evaluations:5432/${EVALUATIONS_SERVICE_POSTGRES_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${EVALUATIONS_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${EVALUATIONS_SERVICE_POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"
      AUTHENTICATION_JWT_APIGATEWAY_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB


  # Starts a container with a Postgres Database for the Evaluations Service.
  postgres-evaluations:
    image: postgres:10.8-alpine
    ports:
      - "25432:5432"
    networks:
      - databases
      - backdoor
    environment:
      POSTGRES_USER: ${EVALUATIONS_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EVALUATIONS_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EVALUATIONS_SERVICE_POSTGRES_DATABASE}

  # ================================================================================
  # Users Service
  # ================================================================================

  # Starts a container with the Evaluations Service.
  users-service:
    image: itbacep/users-service:${USERS_SERVICE_VERSION}
    depends_on:
      - service-registry
      - postgres-users
    networks:
      - services
      - databases
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-users:5432/${USERS_SERVICE_POSTGRES_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${USERS_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USERS_SERVICE_POSTGRES_PASSWORD}
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"
      AUTHENTICATION_JWT_APIGATEWAY_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB
      AUTHENTICATION_JWT_USERSSERVICE_PRIVATEKEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDdCiV3aMzOT8JrfJi6yOb2HE2ncRUGfNYPwZtNJ809X7vP/7Z/0tFLHYLO0wLCA9yIoL7t9YfMpxSCJ0ts+o+kqOqVslDQoqnus8c5OYBpJpVf45VKLTSnuVtTUd16mN3O3QtPBPcQEdNTR8aCFM5Bl99W0rPKDga2HqIoSEgAdDO1DrckjlzoXWjh4bAnwmsgdyNR7Bc7wcMGxT7dQa2LDyLFdVnix8YytaQ/KUALzWAJYV9CFaCAbPQ73EwQEPfQLUSAEFkQ3wLRaDcSAMi2JSu52q/FyCcJrWyyMSBJj6RiAywPByqnM7k+IhI13YkhzfWaIz31dpCQCtgiJ0FPAgMBAAECggEAa2DLdKevnqX2f7rmgw6nzHVRb/8qRJ2Oa9cUt7WXKbKBDXle0de7Hq92ZTzywQeZMbJNLlIxp0SfXN7z8DwEXexFEXWvdrserDwfkvgRHoPE2vE3C/LL+pK7/8zsN+tdDWoqXTe/Qco3C+T5VSYAULMTpxzyhDyuG/jjs4fxmm3xhi5OlUc4Ffh1MMdldkzp2fw2V58dJn1iwUyv/Up/VpxvIihqLcOXY6mRoXsAlFXlClG367QxuAyVZMzb6MtAg/tmTRQ8rCN9d3/piqIdtrF/2dI/B6QfeQNtqvY7o6Sq/lBvPqpv5hPeE6kX9J/nGCbfK95uR3Nh3o5jSWmm8QKBgQD3nx4JXZjZXO+9N04QnahZTWj819OVyg1VWBEb7obfDkhOqJEgQFBg7yadmtI/NwIFaEonJ3N6e5qimuFlEPGMhNFDxJvgxK9xKH1tig61RYP27NwkFvHLhiDMQyRx1t5VX37DdeTtvEOn/jDl8i41EJyGvnacvsk2XT4b1qIdFwKBgQDkhMcwem9Qu3gAfQ1UR011Srp1FjDxpqBGnSu6MPFuirSX/m+cyUgthZ2R1q3glZKQ1OaJihqx9jNeotHGcQeXXW+nFnlqxxk+Dt2LHurYJcAmynPdSqNBmtQlQl3h2tg84rpVtYuFkEs+GRY4fzilZqkk7G9VEx9tRadauDXQiQKBgQCtdNTBksMDYEq/rQIOOaI4DDXDCBy7DLKSWgKCInBvx712/DXM9cBYZq4SMOWeSpYr24Y2LziBUBxeU0gYV+ocmN1OL2dR5/VNuyNBnDf5Wxy51+nNjhUKkIZhD5dz9yP/gcl2ehtHPV3XTARMz3z2xxAeg0TrP+oLHv3m2k7tOQKBgAik2SAFUZadMMHb+RgaBl0McZciOsG5StDA+zl0xn0m9APX1QL6PieyqS4uD6+yGLQvyXSka7QVmwXWZNb7yYy5NRL976PRWiwVxd2QUtPQQb914wIY46oEoEe0hfaYH5vV+7RoRJnNxnrX2hZTAaKICpfh9agjLAonG1h8JVT5AoGBAIl3qIMVbPPmKRveZxJ+17RRveWu+vXD3PbxWxREQMBqFuk+pPemMMoFbSVevs33cOx7m7kZ9zsgs7JkLqjAx2RqL+JtCBgkFVbwd3QMkUS7mKPIljv/cUbUOcpVZmeV6C0UBHPgMyUltbHIhmVI+d4JafTCV384y0Cv0NcRFn1/
      AUTHENTICATION_JWT_USERSSERVICE_ACCESSTOKENDURATION: 300
      AUTHENTICATION_JWT_USERSSERVICE_REFRESHTOKENDURATION: 2592000
      USERSSERVICE_FIRSTUSER_USERNAME: ${USERS_SERVICE_FIRST_USER_USERNAME}
      USERSSERVICE_FIRSTUSER_PASSWORD: ${USERS_SERVICE_FIRST_USER_PASSWORD}

  # Starts a container with a Postgres Database for the Users Service.
  postgres-users:
    image: postgres:10.8-alpine
    ports:
      - "35432:5432"
    networks:
      - databases
      - backdoor
    environment:
      POSTGRES_USER: ${USERS_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_SERVICE_POSTGRES_DATABASE}

  
  # ================================================================================
  # Executor Service
  # ================================================================================

  # Starts a container with the Executors Service
  executor-service:
    image: itbacep/executor-service:${EXECUTOR_SERVICE_VERSION}
    depends_on:
      - kafka
    networks:
      - databases
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"

  
  # ================================================================================
  # LTI Stuff
  # ================================================================================

  # Starts a container with the Evaluations Service.
  lti-service:
    image: itbacep/lti-service:${LTI_SERVICE_VERSION}
    depends_on:
      - service-registry
      - postgres-lti
    networks:
      - services
      - databases
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-lti:5432/${LTI_SERVICE_POSTGRES_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${LTI_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${LTI_SERVICE_POSTGRES_PASSWORD}
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"
      LTISERVICE_APP_STATEHELPER_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB
      LTISERVICE_APP_STATEHELPER_PRIVATEKEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDdCiV3aMzOT8JrfJi6yOb2HE2ncRUGfNYPwZtNJ809X7vP/7Z/0tFLHYLO0wLCA9yIoL7t9YfMpxSCJ0ts+o+kqOqVslDQoqnus8c5OYBpJpVf45VKLTSnuVtTUd16mN3O3QtPBPcQEdNTR8aCFM5Bl99W0rPKDga2HqIoSEgAdDO1DrckjlzoXWjh4bAnwmsgdyNR7Bc7wcMGxT7dQa2LDyLFdVnix8YytaQ/KUALzWAJYV9CFaCAbPQ73EwQEPfQLUSAEFkQ3wLRaDcSAMi2JSu52q/FyCcJrWyyMSBJj6RiAywPByqnM7k+IhI13YkhzfWaIz31dpCQCtgiJ0FPAgMBAAECggEAa2DLdKevnqX2f7rmgw6nzHVRb/8qRJ2Oa9cUt7WXKbKBDXle0de7Hq92ZTzywQeZMbJNLlIxp0SfXN7z8DwEXexFEXWvdrserDwfkvgRHoPE2vE3C/LL+pK7/8zsN+tdDWoqXTe/Qco3C+T5VSYAULMTpxzyhDyuG/jjs4fxmm3xhi5OlUc4Ffh1MMdldkzp2fw2V58dJn1iwUyv/Up/VpxvIihqLcOXY6mRoXsAlFXlClG367QxuAyVZMzb6MtAg/tmTRQ8rCN9d3/piqIdtrF/2dI/B6QfeQNtqvY7o6Sq/lBvPqpv5hPeE6kX9J/nGCbfK95uR3Nh3o5jSWmm8QKBgQD3nx4JXZjZXO+9N04QnahZTWj819OVyg1VWBEb7obfDkhOqJEgQFBg7yadmtI/NwIFaEonJ3N6e5qimuFlEPGMhNFDxJvgxK9xKH1tig61RYP27NwkFvHLhiDMQyRx1t5VX37DdeTtvEOn/jDl8i41EJyGvnacvsk2XT4b1qIdFwKBgQDkhMcwem9Qu3gAfQ1UR011Srp1FjDxpqBGnSu6MPFuirSX/m+cyUgthZ2R1q3glZKQ1OaJihqx9jNeotHGcQeXXW+nFnlqxxk+Dt2LHurYJcAmynPdSqNBmtQlQl3h2tg84rpVtYuFkEs+GRY4fzilZqkk7G9VEx9tRadauDXQiQKBgQCtdNTBksMDYEq/rQIOOaI4DDXDCBy7DLKSWgKCInBvx712/DXM9cBYZq4SMOWeSpYr24Y2LziBUBxeU0gYV+ocmN1OL2dR5/VNuyNBnDf5Wxy51+nNjhUKkIZhD5dz9yP/gcl2ehtHPV3XTARMz3z2xxAeg0TrP+oLHv3m2k7tOQKBgAik2SAFUZadMMHb+RgaBl0McZciOsG5StDA+zl0xn0m9APX1QL6PieyqS4uD6+yGLQvyXSka7QVmwXWZNb7yYy5NRL976PRWiwVxd2QUtPQQb914wIY46oEoEe0hfaYH5vV+7RoRJnNxnrX2hZTAaKICpfh9agjLAonG1h8JVT5AoGBAIl3qIMVbPPmKRveZxJ+17RRveWu+vXD3PbxWxREQMBqFuk+pPemMMoFbSVevs33cOx7m7kZ9zsgs7JkLqjAx2RqL+JtCBgkFVbwd3QMkUS7mKPIljv/cUbUOcpVZmeV6C0UBHPgMyUltbHIhmVI+d4JafTCV384y0Cv0NcRFn1/
      AUTHENTICATION_JWT_APIGATEWAY_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Qold2jMzk/Ca3yYusjm9hxNp3EVBnzWD8GbTSfNPV+7z/+2f9LRSx2CztMCwgPciKC+7fWHzKcUgidLbPqPpKjqlbJQ0KKp7rPHOTmAaSaVX+OVSi00p7lbU1Hdepjdzt0LTwT3EBHTU0fGghTOQZffVtKzyg4Gth6iKEhIAHQztQ63JI5c6F1o4eGwJ8JrIHcjUewXO8HDBsU+3UGtiw8ixXVZ4sfGMrWkPylAC81gCWFfQhWggGz0O9xMEBD30C1EgBBZEN8C0Wg3EgDItiUrudqvxcgnCa1ssjEgSY+kYgMsDwcqpzO5PiISNd2JIc31miM99XaQkArYIidBTwIDAQAB

  # Starts a container with a Postgres Database for the LTI Service.
  postgres-lti:
    image: postgres:10.8-alpine
    ports:
      - "45432:5432"
    networks:
      - databases
      - backdoor
    environment:
      POSTGRES_USER: ${LTI_SERVICE_POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${LTI_SERVICE_POSTGRES_USER}
      POSTGRES_DB: ${LTI_SERVICE_POSTGRES_PASSWORD}

  # Starts a container with the Executors Service
  lti-app:
    image: itbacep/lti-app:${LTI_APP_VERSION}
    ports:
      - "5000:8000"
    depends_on:
      - service-registry
      - lti-service
    networks:
      - dmz
      - services
    environment:
      LTIAPP_EXAMTAKINGURLTEMPLATE: "https://cep.bellotapps.com/take-exam?exam-id=$${exam-id}&access-token=$${access-token}&refresh-token=$${refresh-token}&token-id=$${token-id}"
      eureka.client.serviceUrl.defaultZone: "http://service-registry:8761/eureka/"
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      SPRING_PROFILES_ACTIVE: "prod"


  # ================================================================================
  # Logging and Tracing
  # ================================================================================

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    depends_on:
      - cassandra-zipkin
    networks:
      - dmz
      - services
      - databases
      - backdoor
    environment:
      STORAGE_TYPE: cassandra
      CASSANDRA_CONTACT_POINTS: cassandra-zipkin

  cassandra-zipkin:
    image: cassandra
    networks:
      - databases

  # ================================================================================
  # Service Registry
  # ================================================================================

  service-registry:
    image: itbacep/service-registry:${SERVICE_REGISTRY_VERSION}
    ports:
      - "8761:8761"
    networks:
      - services
      - backdoor
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
  
  # ================================================================================
  # Kafka stuff
  # ================================================================================
  
  # Starts a container with a Kafka instance
  kafka:
    image: confluentinc/cp-kafka:5.1.3
    depends_on:
      - zookeeper
    networks:
      - databases
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # VER QUE ONDA LO DE LAS METRICS DE CONFLUENT

  # Starts a container with a Zookeeper instance
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.3
    networks:
      - databases
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


# ================================================================================
# Networking
# ================================================================================

networks:
  # Network that can be accessed from the outside
  dmz:
    name: dmz
    driver: bridge
  # Network where services are placed
  services:
    name: services
    driver: bridge
    internal: 'true'
  # Network where databases are placed
  databases:
    name: databases
    driver: bridge
    internal: 'true'
  # A network to be used for troubleshooting and debugging 
  # DO NOT USE IN PRODUCTION!!!
  backdoor:
    name: backdoor
    driver: bridge
